### ISSUE TITLE
every thing flagged by avs

### ISSUE THREAD

**Issue by sparta34** [sevagas/macro_pack#49]
hi man your tool is  flagged by all AVs on the planet thanks anyway for sharing

**Comment by sevagas** [comment]
Hi, Not sure to understand the issue here. Are you complaining about macro_pack.exe itself being flagged (it is the payload generator so we do not really care if it is flag, also you should compile it to reduce detection rate). If the problem are the payload themselves, I know, the version with advanced  AV bypass is not distributed.
In either case, this is not a bug.
